name: Build ARM64 Wheels
on:
  push:
    branches: [ latest-features ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'  # Build on x64 but target ARM64
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools
    
    - name: Build wheel
      run: python -m build --wheel
    
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/*.whl
